title: Settings
path: settings
icon: mdi:wrench
cards:
  - type: custom:decluttering-card
    template: header_slim
    variables: 
      - title: Settings

  - type: custom:mod-card
    style: |
      ha-card {
        padding: 8px 16px 0px 16px;
      }
    card:
      type: custom:layout-card
      min_columns: 1
      max_columns: 1
      layout: horizontal
      justify_content: start
      cards:
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.bathroom_ceiling_night
          name: Toalett natt
          icon: mdi:signal-variant                 
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.bathroom_ceiling_night
          label: >
                  [[[
                    return states['input_number.bathroom_ceiling_night'].state;
                  ]]]
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.bedroom_ceiling
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.bedroom_ceiling
          label: >
                  [[[
                    return states['input_number.bedroom_ceiling'].state;
                  ]]]
          name: Sovrum tak
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.bedroom_table_lamps
          name: Sängbordslamp.
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.bedroom_table_lamps
          label: >
                  [[[
                    return states['input_number.bedroom_table_lamps'].state;
                  ]]]
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.bedroom_window
          name: Sovrum fönster
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.bedroom_window
          label: >
                  [[[
                    return states['input_number.bedroom_window'].state;
                  ]]]
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.hallway_ceiling
          name: Hall tak
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.hallway_ceiling
          label: >
                  [[[
                    return states['input_number.hallway_ceiling'].state;
                  ]]]
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.hallway_ceiling_night
          name: Hall tak natt
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.hallway_ceiling_night
          label: >
                  [[[
                    return states['input_number.hallway_ceiling_night'].state;
                  ]]]
        - type: custom:button-card
          template: slider_button_2
          entity: input_number.hallway_table_lamp
          name: Hall bordslampa
          icon: mdi:signal-variant
          custom_fields:
            slider:
              card:
                type: custom:slider-entity-row
                full_row: true
                hide_state: true
                entity: input_number.hallway_table_lamp
          label: >
                  [[[
                    return states['input_number.hallway_table_lamp'].state;
                  ]]]

          